# Generated by Django 2.2.9 on 2020-01-31 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200128_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
