# Generated by Django 2.2.9 on 2020-01-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_added_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-added_on'], 'verbose_name_plural': 'cities'},
        ),
    ]
